# ✅ Gabarito — Programação para Análise de Dados

**Professor:** Domingos M. R. Napolitano  
**Disciplina:** Programação para Análise de Dados  
**Pontuação:** Q1–Q10 × 0,75 pt + Q11–Q15 × 0,50 pt = **10.0 pontos**

---
> 📌 **Documento restrito — uso exclusivo do professor.**


## Instruções

- Execute a **célula de setup** antes de qualquer outra.
- Q1–Q10: substitua cada `____________` pelo código correto.
- Q11–Q15: questões de teste — responsa na folha impressa.

## 📊 Quadro de Pontuação

| Questão | Tipo | Valor | Nota |
|---------|------|------:|-----:|
| Q1  | Completar código    | 0,75 pt | &nbsp; |
| Q2  | Completar código    | 0,75 pt | &nbsp; |
| Q3  | Completar código    | 0,75 pt | &nbsp; |
| Q4  | Completar código    | 0,75 pt | &nbsp; |
| Q5  | Completar código    | 0,75 pt | &nbsp; |
| Q6  | Completar código    | 0,75 pt | &nbsp; |
| Q7  | Completar código    | 0,75 pt | &nbsp; |
| Q8  | Completar código    | 0,75 pt | &nbsp; |
| Q9  | Completar código    | 0,75 pt | &nbsp; |
| Q10 | Completar código    | 0,75 pt | &nbsp; |
| Q11 | Relacionar colunas  | 0,50 pt | &nbsp; |
| Q12 | Escolha alternativa | 0,50 pt | &nbsp; |
| Q13 | Relacionar colunas  | 0,50 pt | &nbsp; |
| Q14 | Escolha alternativa | 0,50 pt | &nbsp; |
| Q15 | Escolha alternativa | 0,50 pt | &nbsp; |
| **Total** | | **10,00 pt** | &nbsp; |

---
## ⚙️ Setup — Execute primeiro!

In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'id_pedido':      [301, 302, 303, 304, 305, 306, 307, 308, 309, 310,
                       311, 312, 313, 314, 315, 316, 317, 318, 319, 320,
                       321, 322, 323, 324, 325],
    'data_pedido':    ['05/01/2024', '18/01/2024', '02/02/2024', '14/02/2024', '25/02/2024',
                       '08/03/2024', '22/03/2024', '03/04/2024', '16/04/2024', '29/04/2024',
                       '10/05/2024', '24/05/2024', '06/06/2024', '19/06/2024', '02/07/2024',
                       '15/07/2024', '28/07/2024', '09/08/2024', '22/08/2024', '04/09/2024',
                       '17/09/2024', '01/10/2024', '14/10/2024', '27/10/2024', '08/11/2024'],
    'cliente':        ['Lucas', 'Mariana', 'Felipe', np.nan, 'Camila',
                       'Rafael', 'Beatriz', 'Diego', 'Amanda', np.nan,
                       'Thiago', 'Larissa', 'Bruno', 'Carolina', 'Mateus',
                       'Juliana', np.nan, 'Pedro', 'Fernanda', 'Eduardo',
                       'Isabela', 'Gabriel', 'Priya', 'Sofia', 'André'],
    'categoria':      ['Eletrônicos', 'Roupas', 'Eletrônicos', 'Casa', 'Esportes',
                       'Eletrônicos', 'Roupas', 'Casa', 'Eletrônicos', 'Livros',
                       'Roupas', 'Esportes', 'Eletrônicos', 'Casa', 'Livros',
                       'Roupas', 'Eletrônicos', 'Esportes', 'Casa', 'Livros',
                       'Roupas', 'Eletrônicos', 'Livros', 'Esportes', 'Casa'],
    'produto':        ['Notebook', 'Camiseta', 'Smartphone', 'Cafeteira', 'Bicicleta',
                       'Tablet', 'Calça', 'Aspirador', 'Monitor', 'Python para Dados',
                       'Vestido', 'Haltere', 'Headphone', 'Luminária', 'Machine Learning',
                       'Tênis', 'Smartwatch', 'Mochila', 'Tapete', 'Estatística',
                       'Jaqueta', 'Câmera', 'IA Prática', 'Garrafa', 'Travesseiro'],
    'quantidade':     [3, 2, 1, 2, 1, 2, 4, np.nan, 1, 3,
                       2, 5, 2, np.nan, 2, 3, 1, 2, 4, 1,
                       2, 1, 3, 6, 2],
    'preco_unitario': [3500.0,  89.0, 1200.0,  380.0, 1800.0,
                        800.0, 149.0,  590.0, 1500.0,   89.0,
                        199.0, 150.0,  350.0,  120.0,   95.0,
                        299.0, 600.0,  220.0,  210.0,   79.0,
                        259.0, 2200.0, 110.0,   65.0,   85.0],
    'desconto_pct':   [0.05, np.nan, 0.10, 0.00, 0.15,
                       np.nan, 0.05, 0.00, 0.10, 0.00,
                       0.05, 0.15, 0.10, 0.00, np.nan,
                       0.05, 0.20, 0.00, 0.10, np.nan,
                       0.05, 0.15, 0.00, 0.10, 0.05],
    'status':         ['Entregue', 'Entregue', 'Em Trânsito', 'Entregue', 'Cancelado',
                       'Entregue', 'Entregue', 'Em Trânsito', 'Entregue', 'Entregue',
                       'Em Trânsito', 'Entregue', 'Cancelado', 'Entregue', 'Entregue',
                       'Em Trânsito', 'Entregue', 'Entregue', 'Cancelado', 'Entregue',
                       'Entregue', 'Em Trânsito', 'Entregue', 'Entregue', 'Em Trânsito'],
    'avaliacao':      ['Bom', 'Excelente', 'Regular', 'Bom', np.nan,
                       'Excelente', 'Bom', 'Regular', 'Excelente', 'Bom',
                       np.nan, 'Excelente', 'Regular', 'Bom', 'Excelente',
                       'Regular', 'Bom', 'Excelente', np.nan, 'Ruim',
                       'Bom', 'Excelente', 'Regular', 'Bom', 'Excelente'],
})

print("DataFrame criado com sucesso!")
print(f"Shape: {df.shape}")
df.head()

DataFrame criado com sucesso!
Shape: (25, 10)

,id_pedido,data_pedido,cliente,categoria,produto,quantidade,preco_unitario,desconto_pct,status,avaliacao
0,301,05/01/2024,Lucas,Eletrônicos,Notebook,3.0,3500.0,0.05,Entregue,Bom
1,302,18/01/2024,Mariana,Roupas,Camiseta,2.0,89.0,NaN,Entregue,Excelente
2,303,02/02/2024,Felipe,Eletrônicos,Smartphone,1.0,1200.0,0.10,Em Trânsito,Regular
3,304,14/02/2024,NaN,Casa,Cafeteira,2.0,380.0,0.00,Entregue,Bom
4,305,25/02/2024,Camila,Esportes,Bicicleta,1.0,1800.0,0.15,Cancelado,NaN

---
## Parte 1 — Questões de Código (Q1–Q10)

### Questão 1 — 0,75 pt

**Resumo Geral e Tipos de Dados**

Escreva os dois comandos para: **(a)** exibir o resumo geral do DataFrame (tipos de cada coluna, contagem de não-nulos e uso de memória) e **(b)** listar o tipo de dado de cada coluna.

In [2]:
# (a) Resumo geral
df.info()

# (b) Tipo de dado de cada coluna
df.dtypes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_pedido       25 non-null     int64
 1   data_pedido     25 non-null     object
 2   cliente         22 non-null     object
 3   categoria       25 non-null     object
 4   produto         25 non-null     object
 5   quantidade      23 non-null     float64
 6   preco_unitario  25 non-null     float64
 7   desconto_pct    21 non-null     float64
 8   status          25 non-null     object
 9   avaliacao       22 non-null     object
dtypes: float64(3), int64(1), object(6)
memory usage: 2.1+ KB

id_pedido           int64
data_pedido        object
cliente            object
categoria          object
produto            object
quantidade        float64
preco_unitario    float64
desconto_pct      float64
status             object
avaliacao          object
dtype: object

### Questão 2 — 0,75 pt

**Filtro com Operador de Diferença**

Filtre e exiba apenas os pedidos cujo `status` **não seja** `'Cancelado'`, mostrando as colunas `id_pedido`, `produto`, `categoria` e `preco_unitario`.

In [3]:
resultado = df[df['status'] != 'Cancelado']
resultado[['id_pedido', 'produto', 'categoria', 'preco_unitario']]

    id_pedido            produto    categoria  preco_unitario
0         301           Notebook  Eletrônicos          3500.0
1         302           Camiseta       Roupas            89.0
2         303         Smartphone  Eletrônicos          1200.0
3         304          Cafeteira         Casa           380.0
5         306             Tablet  Eletrônicos           800.0
6         307              Calça       Roupas           149.0
7         308          Aspirador         Casa           590.0
8         309            Monitor  Eletrônicos          1500.0
9         310  Python para Dados       Livros            89.0
10        311            Vestido       Roupas           199.0
11        312            Haltere     Esportes           150.0
13        314          Luminária         Casa           120.0
14        315   Machine Learning       Livros            95.0
15        316              Tênis       Roupas           299.0
16        317         Smartwatch  Eletrônicos           600.0
17        318            Mochila     Esportes           220.0
19        320        Estatística       Livros            79.0
20        321            Jaqueta       Roupas           259.0
21        322             Câmera  Eletrônicos          2200.0
22        323         IA Prática       Livros           110.0
23        324            Garrafa     Esportes            65.0
24        325        Travesseiro         Casa            85.0

### Questão 3 — 0,75 pt

**Criação de Coluna Derivada**

Crie a coluna `valor_bruto` = `quantidade` × `preco_unitario`.

> ⚠️ **Atenção:** esta coluna será usada nas questões Q7 e Q9 — execute esta célula antes de continuar.

In [4]:
df['valor_bruto'] = df['quantidade'] * df['preco_unitario']
df[['produto', 'quantidade', 'preco_unitario', 'valor_bruto']].head()

      produto  quantidade  preco_unitario  valor_bruto
0    Notebook         3.0          3500.0      10500.0
1    Camiseta         2.0            89.0        178.0
2  Smartphone         1.0          1200.0       1200.0
3   Cafeteira         2.0           380.0        760.0
4   Bicicleta         1.0          1800.0       1800.0

### Questão 4 — 0,75 pt

**Máscara Booleana Composta com `|` (OU)**

Complete o código para filtrar pedidos da categoria `'Eletrônicos'` **OU** com `preco_unitario >= 800`.

In [5]:
mascara = (df['categoria'] == 'Eletrônicos') | (df['preco_unitario'] >= 800)
resultado = df[mascara][['id_pedido', 'categoria', 'produto', 'preco_unitario']]
print(f"Pedidos encontrados: {len(resultado)}")
resultado

Pedidos encontrados: 8

    id_pedido    categoria     produto  preco_unitario
0         301  Eletrônicos    Notebook          3500.0
2         303  Eletrônicos  Smartphone          1200.0
4         305     Esportes   Bicicleta          1800.0
5         306  Eletrônicos      Tablet           800.0
8         309  Eletrônicos     Monitor          1500.0
12        313  Eletrônicos   Headphone           350.0
16        317  Eletrônicos  Smartwatch           600.0
21        322  Eletrônicos      Câmera          2200.0

### Questão 5 — 0,75 pt

**Tratamento de Valores Ausentes**

Complete o código para tratar os NaN: `desconto_pct` com `0.0` e `quantidade` com a **mediana** global da coluna.

In [6]:
df_trat = df.copy()

# desconto_pct → 0.0
df_trat['desconto_pct'] = df_trat['desconto_pct'].fillna(0.0)

# quantidade → mediana global
df_trat['quantidade'] = df_trat['quantidade'].fillna(df_trat['quantidade'].median())

print(df_trat[['desconto_pct', 'quantidade']].isnull().sum())

desconto_pct    0
quantidade      0
dtype: int64

### Questão 6 — 0,75 pt

**Conversão de Datas e Extração de Componentes**

Complete o código para: (1) converter `data_pedido` para `datetime`; (2) extrair o **ano** em `ano_pedido`; (3) extrair o **dia da semana** em `dia_semana` (0 = Segunda, 6 = Domingo).

In [7]:
df['data_pedido'] = pd.to_datetime(df['data_pedido'], format='%d/%m/%Y')
df['ano_pedido']  = df['data_pedido'].dt.year
df['dia_semana']  = df['data_pedido'].dt.dayofweek
df[['produto', 'data_pedido', 'ano_pedido', 'dia_semana']].head()

      produto data_pedido  ano_pedido  dia_semana
0    Notebook  2024-01-05        2024           4
1    Camiseta  2024-01-18        2024           3
2  Smartphone  2024-02-02        2024           4
3   Cafeteira  2024-02-14        2024           2
4   Bicicleta  2024-02-25        2024           6

### Questão 7 — 0,75 pt

**Agrupamento com `.agg()` e Ordenação**

Complete o código para agrupar por `categoria` e calcular, em uma única chamada `.agg()`, a **soma** de `valor_bruto` (→ `total_vendas`) e a **contagem** de `id_pedido` (→ `qtd_pedidos`). Ordene pelo total de vendas de forma **decrescente**.

In [8]:
resumo = df.groupby('categoria').agg(
    total_vendas = ('valor_bruto', 'sum'),
    qtd_pedidos  = ('id_pedido',   'count')
).sort_values('total_vendas', ascending=False)
resumo

             total_vendas  qtd_pedidos
categoria
Eletrônicos       18300.0            7
Esportes           3380.0            4
Roupas             2587.0            5
Casa               1770.0            5
Livros              866.0            4

### Questão 8 — 0,75 pt

**Seleção com `.loc` e Renomeação**

Use `.loc` para selecionar as colunas `produto`, `categoria`, `preco_unitario` e `avaliacao` dos pedidos com `avaliacao == 'Excelente'`. Em seguida, renomeie `preco_unitario` para `'preço'`.

In [9]:
selecionado = df.loc[
    df['avaliacao'] == 'Excelente',
    ['produto', 'categoria', 'preco_unitario', 'avaliacao']
]
selecionado = selecionado.rename(columns={'preco_unitario': 'preço'})
selecionado

             produto    categoria   preço  avaliacao
1           Camiseta       Roupas    89.0  Excelente
5             Tablet  Eletrônicos   800.0  Excelente
8            Monitor  Eletrônicos  1500.0  Excelente
11           Haltere     Esportes   150.0  Excelente
14  Machine Learning       Livros    95.0  Excelente
17           Mochila     Esportes   220.0  Excelente
21            Câmera  Eletrônicos  2200.0  Excelente
24       Travesseiro         Casa    85.0  Excelente

### Questão 9 — 0,75 pt

**Pivot Table — Preço Médio por Categoria e Status**

Complete o código para criar uma pivot table com o **preço médio** (`preco_unitario`) por `categoria` (linhas) e `status` (colunas). Use `fill_value=0` e arredonde para 2 casas decimais.

In [10]:
pivot = pd.pivot_table(
    df,
    values='preco_unitario',
    index='categoria',
    columns='status',
    aggfunc='mean',
    fill_value=0
).round(2)
pivot

status       Cancelado  Em Trânsito  Entregue
categoria
Casa             210.0        337.5    250.00
Eletrônicos      350.0       1700.0   1600.00
Esportes        1800.0          0.0    145.00
Livros             0.0          0.0     93.25
Roupas             0.0        249.0    165.67

### Questão 10 — 0,75 pt

**Variável Ordinal + Discretização Manual + Análise por Faixa**

Complete o script em três partes:

**(a)** Converta `avaliacao` para categórica **ordinal** (ordem: `Ruim < Regular < Bom < Excelente`)

**(b)** Discretize `preco_unitario` em **4 faixas manuais** com `pd.cut()` usando os limites `[0, 200, 500, 1200, 4000]` e labels `['Econômica', 'Intermediária', 'Premium', 'Luxo']`

**(c)** Calcule a **média de `preco_unitario`** por `faixa_preco` com `groupby`

In [11]:
# (a) Categorical ordinal
ordem = ['Ruim', 'Regular', 'Bom', 'Excelente']
df['avaliacao'] = pd.Categorical(
    df['avaliacao'], categories=ordem, ordered=True
)

# (b) Faixas manuais com pd.cut
df['faixa_preco'] = pd.cut(
    df['preco_unitario'],
    bins=[0, 200, 500, 1200, 4000],
    labels=['Econômica', 'Intermediária', 'Premium', 'Luxo'],
    include_lowest=True
)

# (c) Média de preco_unitario por faixa
df.groupby('faixa_preco', observed=True)['preco_unitario'].mean().round(2)

faixa_preco
Econômica         111.82
Intermediária     286.33
Premium           797.50
Luxo             2250.00
Name: preco_unitario, dtype: float64

---
## Parte 2 — Questões de Teste (Q11–Q15)

### Questão 11 — 0,50 pt  ·  *Relacionar Colunas*

**Relacionar Colunas — Operações de Inspeção e Manutenção**

**Relacione cada script com a descrição correta.**

| # | Script | Letra |
|---|--------|:-----:|
| 1 | `df.describe()` | **B** |
| 2 | `df.drop('col', axis=1)` | **A** |
| 3 | `df['col'].unique()` | **C** |
| 4 | `df.duplicated().sum()` | **D** |
| 5 | `df.reset_index(drop=True)` | **E** |

| Letra | Descrição |
|:-----:|-----------|
| A | Remove uma coluna do DataFrame (retorna cópia) |
| B | Gera estatísticas descritivas das colunas numéricas |
| C | Retorna os valores únicos de uma coluna como array |
| D | Conta o número de linhas duplicadas |
| E | Reinicia o índice para a sequência padrão 0, 1, 2… |

### Questão 12 — 0,50 pt  ·  *Escolha Alternativa*

**Combinação de DataFrames — pd.merge**

**Para combinar `df_pedidos` com `df_clientes` usando `'id_cliente'` como chave, mantendo todos os pedidos mesmo sem correspondência em `df_clientes`, qual comando está correto?**

- A) `how='inner'` — mantém apenas as linhas com correspondência nos dois DataFrames, perdendo pedidos sem cliente
- B) `pd.merge(df_clientes, df_pedidos, ...)` — a ordem importa: `how='left'` preserva o lado esquerdo, que aqui seria `df_clientes`
- **C) `pd.merge(df_pedidos, df_clientes, on='id_cliente', how='left')` ✅ — `df_pedidos` à esquerda + `how='left'` preserva todos os pedidos**
- D) `pd.concat(axis=1)` — empilha colunas lateralmente sem usar chave de relacionamento

**Resposta: C**

### Questão 13 — 0,50 pt  ·  *Relacionar Colunas*

**Relacionar Colunas — Transformações de Colunas**

**Relacione cada script com a descrição correta.**

| # | Script | Letra |
|---|--------|:-----:|
| 1 | `df.rename(columns={'old': 'new'})` | **B** |
| 2 | `df['col'].apply(lambda x: x * 2)` | **A** |
| 3 | `df['col'].str.contains('padrão')` | **D** |
| 4 | `np.where(df['col'] > 0, 'Pos', 'Neg')` | **C** |

| Letra | Descrição |
|:-----:|-----------|
| A | Aplica uma função Python a cada elemento da coluna |
| B | Renomeia colunas usando um dicionário (retorna cópia) |
| C | Cria um array condicional sem loop — substitui `if/else` vetorizado |
| D | Retorna máscara booleana indicando quais strings contêm o padrão |

### Questão 14 — 0,50 pt  ·  *Escolha Alternativa*

**Ordenação com Critérios Mistos — sort_values**

**Para ordenar `df` por `preco_unitario` de forma **decrescente** e, em caso de empate, por `categoria` de forma **crescente**, qual comando está correto?**

- A) `ascending=False` aplica o mesmo critério a **todas** as colunas — `categoria` também ficaria decrescente
- **B) `df.sort_values(['preco_unitario', 'categoria'], ascending=[False, True])` ✅ — lista de booleans, um por coluna**
- C) `.sort_values()` não aceita dois argumentos posicionais de colunas separados por vírgula — `'categoria'` seria interpretado como parâmetro `axis`
- D) `order_by` não existe em pandas (é sintaxe SQL)

**Resposta: B**

### Questão 15 — 0,50 pt  ·  *Escolha Alternativa*

**Diferença entre pd.concat com axis=0 e axis=1**

**Qual é a diferença entre `pd.concat([df1, df2], axis=0)` e `pd.concat([df1, df2], axis=1)`?**

- A) Errado — `axis=1` combina colunas, não reordena linhas
- **B) `axis=0` empilha verticalmente (novas linhas); `axis=1` combina lateralmente (novas colunas) ✅**
- C) Invertido — `axis=0` é vertical (ao longo das linhas), `axis=1` é horizontal (ao longo das colunas)
- D) O pandas não detecta automaticamente — o parâmetro `axis` é obrigatório para definir a direção

**Resposta: B**