<img src="https://keystoneacademic-res.cloudinary.com/image/upload/c_pad,w_640,h_304/dpr_auto/f_auto/q_auto/v1/element/94/94774_thumb.png" width=300>

# Programação para Análise de Dados

## Aula 4: Transformação de Dados - Parte II

### Professor: Carlos E. Leal de Castro

## Setup Inicial

### Importação das bibliotecas

Digite em sua célula:

```python
import pandas as pd
import numpy as np
```

In [1]:
# Importando a biblioteca pandas
import pandas as pd
import numpy as np

### Crie o DataFrame de Vendas

```python
data_vendas = {'ID_Vendedor': [101, 102, 101, 
                               103, 102, 101],
               'Produto': ['A', 'B', 'A', 'C', 'B', 'B'],
               'Quantidade': [10, 5, 8, 3, 7, 5],
               'Preco_Unitario': [12.5, 20.0, 12.5, 
                                  50.0, 20.0, 20.0]}
df_vendas = pd.DataFrame(data_vendas)
df_vendas.head()
```

In [2]:
data_vendas = {'ID_Vendedor': [101, 102, 101, 
                               103, 102, 101],
               'Produto': ['A', 'B', 'A', 'C', 'B', 'B'],
               'Quantidade': [10, 5, 8, 3, 7, 5],
               'Preco_Unitario': [12.5, 20.0, 12.5, 
                                  50.0, 20.0, 20.0]}
df_vendas = pd.DataFrame(data_vendas)

In [3]:
print('Saída:')
df_vendas.head()

Saída:

   ID_Vendedor Produto  Quantidade  Preco_Unitario
0          101       A          10            12.5
1          102       B           5            20.0
2          101       A           8            12.5
3          103       C           3            50.0
4          102       B           7            20.0

## Crie o DataFrame de Vendedores

```python
data_vendedores = {'ID_Vendedor': [101, 102, 103, 104],
                   'Nome_Vendedor': ['João', 'Maria', 'Pedro', 'Ana'],
                   'Regiao': ['Sudeste', 'Nordeste', 'Sudeste', 'Sul']}
df_vendedores = pd.DataFrame(data_vendedores)
df_vendedores.head()
```

In [4]:
data_vendedores = {'ID_Vendedor': [101, 102, 103, 104,111],
                   'Nome_Vendedor': ['João', 'Maria', 'Pedro', 'Ana',np.nan],
                   'Regiao': ['Sudeste', 'Nordeste', 'Sudeste', 'Sul',np.nan]}
df_vendedores = pd.DataFrame(data_vendedores)

In [5]:
display(df_vendedores)

   ID_Vendedor Nome_Vendedor    Regiao
0          101          João   Sudeste
1          102         Maria  Nordeste
2          103         Pedro   Sudeste
3          104           Ana       Sul
4          111           NaN       NaN

##  Operações com Colunas e Linhas


- **Criando Novas Colunas**: Uma das operações mais comuns é criar uma nova coluna a partir de outras existentes.
    - **Exemplo**: Calcular o valor total de cada venda (Quantidade * Preço_Unitario).

In [6]:
# Criando uma nova coluna 'Valor_Total'
df_vendas['Valor_Total'] = df_vendas['Quantidade'] * df_vendas['Preco_Unitario']
print("DataFrame com a nova coluna 'Valor_Total':")
display(df_vendas)

DataFrame com a nova coluna 'Valor_Total':

   ID_Vendedor Produto  Quantidade  Preco_Unitario  Valor_Total
0          101       A          10            12.5        125.0
1          102       B           5            20.0        100.0
2          101       A           8            12.5        100.0
3          103       C           3            50.0        150.0
4          102       B           7            20.0        140.0
5          101       B           5            20.0        100.0

##  Operações com Colunas e Linhas

- **Removendo Colunas e Linhas**: Utilização do método .drop().

In [7]:
# Removendo a coluna 'Preco_Unitario' (axis=1 para indicar coluna)
df_vendas_sem_preco = df_vendas.drop('Preco_Unitario', axis=1)
print("\nDataFrame após remover a coluna 'Preco_Unitario':")
display(df_vendas_sem_preco)

DataFrame após remover a coluna 'Preco_Unitario':

   ID_Vendedor Produto  Quantidade  Valor_Total
0          101       A          10        125.0
1          102       B           5        100.0
2          101       A           8        100.0
3          103       C           3        150.0
4          102       B           7        140.0
5          101       B           5        100.0

In [8]:
# Removendo linha
df_vendedores = df_vendedores.drop(4) # 4 é o indice da linha que quero remover
df_vendedores

   ID_Vendedor Nome_Vendedor    Regiao
0          101          João   Sudeste
1          102         Maria  Nordeste
2          103         Pedro   Sudeste
3          104           Ana       Sul

##  Operações com Colunas e Linhas

- **Renomeando Colunas**: A importância de nomes claros e o uso de .rename().

In [9]:
# Renomeando colunas para um padrão mais claro
df_renomeado = df_vendas.rename(columns={'Quantidade': 'Qtd_Vendida', 'Produto': 'Nome_Produto'})
print("\nDataFrame com colunas renomeadas:")
display(df_renomeado)

DataFrame com colunas renomeadas:

   ID_Vendedor Nome_Produto  Qtd_Vendida  Preco_Unitario  Valor_Total
0          101            A           10            12.5        125.0
1          102            B            5            20.0        100.0
2          101            A            8            12.5        100.0
3          103            C            3            50.0        150.0
4          102            B            7            20.0        140.0
5          101            B            5            20.0        100.0

##  Operações com Colunas e Linhas

- **Aplicação de Funções**: Uso do .apply() para transformações complexas em colunas.

In [10]:
# Aplicando uma função para criar uma coluna de comissão (10% do valor total)
def calcular_comissao(valor):
    return valor * 0.10

df_vendas['Comissao'] = df_vendas['Valor_Total'].apply(calcular_comissao)
print("\nDataFrame com a coluna 'Comissao':")
df_vendas.head(2)

DataFrame com a coluna 'Comissao':

   ID_Vendedor Produto  Quantidade  Preco_Unitario  Valor_Total  Comissao
0          101       A          10            12.5        125.0      12.5
1          102       B           5            20.0        100.0      10.0

###  Exercício Prático
Crie uma nova coluna chamada Preco_com_Imposto no df_vendas que adicione 5% de imposto sobre o Preco_Unitario. Em seguida, remova a coluna Comissao.

In [11]:
def imposto(valor):
    return valor * (1+5/100)

df_vendas['Preco_com_Imposto'] = df_vendas['Preco_Unitario'].apply(imposto)
df_vendas_sem_comissao = df_vendas.drop(columns=['Comissao'])
df_vendas_sem_comissao.head()

,ID_Vendedor,Produto,Quantidade,Preco_Unitario,Valor_Total,Preco_com_Imposto
0,101,A,10,12.5,125.0,13.125
1,102,B,5,20.0,100.0,21.000
2,101,A,8,12.5,100.0,13.125
3,103,C,3,50.0,150.0,52.500
4,102,B,7,20.0,140.0,21.000

## Merge, Join e Concatenação

- Introdução: Combinar DataFrames é fundamental para a análise de dados.
- O pandas oferece três funções principais para isso: concat, merge e join.
    - **pd.concat()**: "Empilha" DataFrames, seja verticalmente (novas linhas) ou horizontalmente (novas colunas).
    - **pd.merge()**: Combina DataFrames com base em valores de colunas comuns (chaves), similar aos JOINs de SQL.
        - Tipos de merge: inner (padrão), outer, left, right.
    - .join(): Uma forma mais simples de combinar DataFrames com base nos seus índices.

In [12]:
# Combinando df_vendas e df_vendedores usando uma chave comum 'ID_Vendedor'
# O 'how="left"' garante que todas as vendas sejam mantidas, mesmo que um vendedor não esteja na outra tabela.
df_completo = pd.merge(df_vendas, df_vendedores, on='ID_Vendedor', how='left')
print("DataFrame combinado (vendas com informações dos vendedores):")
display(df_completo)

DataFrame combinado (vendas com informações dos vendedores):

,ID_Vendedor,Produto,Quantidade,Preco_Unitario,Valor_Total,Comissao,Preco_com_Imposto,Nome_Vendedor,Regiao
0,101,A,10,12.5,125.0,12.5,13.125,João,Sudeste
1,102,B,5,20.0,100.0,10.0,21.000,Maria,Nordeste
2,101,A,8,12.5,100.0,10.0,13.125,João,Sudeste
3,103,C,3,50.0,150.0,15.0,52.500,Pedro,Sudeste
4,102,B,7,20.0,140.0,14.0,21.000,Maria,Nordeste
5,101,B,5,20.0,100.0,10.0,21.000,João,Sudeste

### Exercício Prático 2
Imagine um novo DataFrame `df_metas` com 
```python
{'ID_Vendedor': [101, 102, 103], 'Meta_Vendas': [200, 150, 180]}
```
Use o merge para adicionar a meta de cada vendedor ao df_completo. Qual tipo de merge seria mais apropriado se quiséssemos ver todos os vendedores, mesmo os que não têm vendas?

##  Agrupamento e Agregação

- O que é Agrupamento? É o processo de dividir os dados em grupos com base em algum critério. No pandas, usamos o método .groupby()
- O Processo "Split-Apply-Combine":
    - Split: Os dados são divididos em grupos.
    - Apply: Uma função é aplicada a cada grupo independentemente (soma, média, contagem, etc.).
    - Combine: Os resultados são combinados em uma nova estrutura de dados.
- Funções de Agregação Comuns: .sum(), .mean(), .count(), .max(), .min().
- Agregações Múltiplas: O método .agg() permite aplicar várias funções de uma só vez.

- Agrupar por Nome_Vendedor e somar o Valor_Total vendido por cada um:

In [13]:
df_completo.groupby("Nome_Vendedor")["Valor_Total"].sum()

Nome_Vendedor
João     325.0
Maria    240.0
Pedro    150.0
Name: Valor_Total, dtype: float64

- Agrupar por duas chaves (Produto, Regiao) e contar linhas:

In [14]:
df_completo.groupby(["Produto", "Regiao"]).size()

Produto  Regiao
A        Sudeste     2
B        Nordeste    2
         Sudeste     1
C        Sudeste     1
dtype: int64

### Processo Split–Apply–Combine

- **Objetivo**: obter, para cada Produto, a soma da Quantidade e a média do Preco_Unitario.

- **Split**: dividir por Produto

- **Apply**: aplicar soma e média

- **Combine**: juntar os resultados em um DataFrame

In [15]:
(
    df_completo
      .groupby("Produto")
      .agg(Quantidade_total=("Quantidade", "sum"),
           Preco_medio=("Preco_Unitario", "mean"))
      .reset_index()
)

  Produto  Quantidade_total  Preco_medio
0       A                18         12.5
1       B                17         20.0
2       C                 3         50.0

### Funções de agregação comuns
a) `.sum()` — quantidade total por Produto

In [16]:
df_completo.groupby("Produto")["Quantidade"].sum()

Produto
A    18
B    17
C     3
Name: Quantidade, dtype: int64

b) `.mean()` — preço unitário médio por Produto

In [17]:
df_completo.groupby("Produto")["Preco_Unitario"].mean()

Produto
A    12.5
B    20.0
C    50.0
Name: Preco_Unitario, dtype: float64

c) `.count()` — número de vendas por Regiao

In [20]:
df_completo.groupby("Regiao")["ID_Vendedor"].count()

Regiao
Nordeste    2
Sudeste     4
Name: ID_Vendedor, dtype: int64

d) `.max()` e `.min()` — maior e menor Valor_Total por Nome_Vendedor

In [21]:
df_completo.groupby("Nome_Vendedor")["Valor_Total"].agg(["max", "min"])

                 max    min
Nome_Vendedor
João           125.0  100.0
Maria          140.0  100.0
Pedro          150.0  150.0

### Agregações múltiplas com `.agg()`

a) Usando dicionário (gera colunas multi-índice)

In [22]:
df_completo.groupby("Produto").agg({
    "Quantidade": ["sum", "mean"],
    "Valor_Total": ["sum", "max"],
})

        Quantidade           Valor_Total
               sum      mean         sum    max
Produto
A               18  9.000000       225.0  125.0
B               17  5.666667       340.0  140.0
C                3  3.000000       150.0  150.0

b) Usando Named Aggregations (colunas já “achatadas” e nomeadas)

In [23]:
df_completo.groupby("Produto").agg(
    Qtde_total=("Quantidade", "sum"),
    Qtde_media=("Quantidade", "mean"),
    Receita_total=("Valor_Total", "sum"),
    Receita_max=("Valor_Total", "max"),
).reset_index()

  Produto  Qtde_total  Qtde_media  Receita_total  Receita_max
0       A          18    9.000000          225.0        125.0
1       B          17    5.666667          340.0        140.0
2       C           3    3.000000          150.0        150.0

c) Transform (mesma forma do original; útil para criar colunas “por grupo”):

In [27]:
df_completo["pct_da_receita_do_vendedor"] = (
    df_completo["Valor_Total"] /
    df_completo.groupby("Nome_Vendedor")["Valor_Total"].transform("sum")
)
df_completo.head()

,ID_Vendedor,Produto,Quantidade,Preco_Unitario,Valor_Total,Comissao,Preco_com_Imposto,Nome_Vendedor,Regiao,pct_da_receita_do_vendedor
0,101,A,10,12.5,125.0,12.5,13.125,João,Sudeste,0.384615
1,102,B,5,20.0,100.0,10.0,21.000,Maria,Nordeste,0.416667
2,101,A,8,12.5,100.0,10.0,13.125,João,Sudeste,0.307692
3,103,C,3,50.0,150.0,15.0,52.500,Pedro,Sudeste,1.000000
4,102,B,7,20.0,140.0,14.0,21.000,Maria,Nordeste,0.583333

### Exercício Prático
Usando o
```python
df_completo
```
calcule o total de vendas (Valor_Total) por Regiao. Qual região teve o maior faturamento?

## Pivot Tables e Reshaping

- **Remodelar (Reshaping)**: Alterar a estrutura de um DataFrame para uma melhor visualização ou análise.
- **Tabelas Dinâmicas (pivot_table)**: Uma de resumir e reorganizar dados, similar às tabelas dinâmicas do Excel.

#### Componentes Principais:
- `index`: O que se tornará o novo índice do DataFrame.
- `columns`: Os valores desta coluna se tornarão as novas colunas.
- `values`: Os valores a serem agregados.
- `aggfunc`: A função de agregação a ser aplicada (padrão é a média).

In [30]:
# Criando uma tabela dinâmica para ver o total de vendas por vendedor em cada região
pivot_vendas_regiao = df_completo.pivot_table(index='Nome_Vendedor',
                                              columns='Regiao',
                                              values='Valor_Total',
                                              aggfunc='sum',
                                              fill_value=0) # Preenche NaN com 0

print("Tabela dinâmica de Vendas por Vendedor e Região:")
display(pivot_vendas_regiao)

Tabela dinâmica de Vendas por Vendedor e Região:

Regiao         Nordeste  Sudeste
Nome_Vendedor
João                0.0    325.0
Maria             240.0      0.0
Pedro               0.0    150.0

#### Exercício
Crie uma `pivot_table` que mostre a Quantidade total de cada Produto vendida por cada Nome_Vendedor.

In [39]:
pivot_qnt_vendas = df_completo.pivot_table(index='Produto',
                                              columns="Nome_Vendedor",
                                              values='Quantidade',
                                              aggfunc='sum',
                                              fill_value=0)

print("Tabela dinâmica de Quantidade por Vendedor e Produto:")
display(pivot_qnt_vendas)

Tabela dinâmica de Quantidade por Vendedor e Produto:

Nome_Vendedor  João  Maria  Pedro
Produto
A                18      0      0
B                 5     12      0
C                 0      0      3