# ✅ Gabarito — Programação para Análise de Dados

**Disciplina:** Programação para Análise de Dados  
**Professor:** Carlos E. Leal de Castro  
**Pontuação total:** 10,0 pontos

---

> 📌 **Use esse documento após a realização da LE.**

| Dificuldade | Questões | Pts/Questão | Total |
|---|---|---|---|
| 🟢 Fácil | Q1 – Q10 | 0,3 | 3,0 pts |
| 🟡 Médio | Q11 – Q15 | 0,6 | 3,0 pts |
| 🔴 Difícil | Q16 – Q20 | 0,8 | 4,0 pts |
| **Total** | **20** | — | **10,0 pts** |

## ⚙️ Célula de Setup

In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'id_pedido':        [1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010,
                         1011, 1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020],
    'data_pedido':      ['15/01/2024', '23/01/2024', '02/02/2024', '14/02/2024', '28/02/2024',
                         '05/03/2024', '19/03/2024', '01/04/2024', '12/04/2024', '25/04/2024',
                         '03/05/2024', '17/05/2024', '29/05/2024', '07/06/2024', '20/06/2024',
                         '04/07/2024', '18/07/2024', '02/08/2024', '16/08/2024', '30/08/2024'],
    'vendedor':         ['Alice', 'Bruno', 'Alice', np.nan, 'Carlos',
                         'Bruno', 'Alice', 'Carlos', np.nan, 'Bruno',
                         'Alice', 'Carlos', 'Bruno', 'Alice', np.nan,
                         'Carlos', 'Bruno', 'Alice', 'Carlos', 'Bruno'],
    'regiao':           ['Sudeste', 'Nordeste', 'Sudeste', 'Sul', 'Centro-Oeste',
                         'Sudeste', 'Norte', 'Nordeste', 'Sul', 'Sudeste',
                         'Centro-Oeste', 'Norte', 'Nordeste', 'Sudeste', 'Sul',
                         'Sudeste', 'Nordeste', 'Norte', 'Sul', 'Centro-Oeste'],
    'produto':          ['Notebook', 'Geladeira', 'Smartphone', 'TV 55"', 'Cadeira Gamer',
                         'Notebook', 'Tablet', 'Geladeira', 'Smartphone', 'TV 55"',
                         'Notebook', 'Cadeira Gamer', 'Tablet', 'Geladeira', 'Notebook',
                         'Smartphone', 'TV 55"', 'Tablet', 'Cadeira Gamer', 'Geladeira'],
    'categoria':        ['Eletrônico', 'Eletrodoméstico', 'Eletrônico', 'Eletrônico', 'Móvel',
                         'Eletrônico', 'Eletrônico', 'Eletrodoméstico', 'Eletrônico', 'Eletrônico',
                         'Eletrônico', 'Móvel', 'Eletrônico', 'Eletrodoméstico', 'Eletrônico',
                         'Eletrônico', 'Eletrônico', 'Eletrônico', 'Móvel', 'Eletrodoméstico'],
    'quantidade':       [2, 1, 3, 1, 4, 2, 5, np.nan, 2, 1,
                         3, 2, 1, np.nan, 2, 4, 1, 3, 2, 1],
    'preco_unitario':   [3500.0, 2800.0, 1200.0, 4500.0,  750.0,
                         3600.0,  900.0, 2750.0, 1150.0, 4200.0,
                         3400.0,  800.0,  950.0, 2900.0, 3700.0,
                         1100.0, 4300.0,  880.0,  720.0, 2650.0],
    'desconto_pct':     [0.05, np.nan, 0.10, 0.00, 0.15,
                         0.05, np.nan, 0.00, 0.10, 0.05,
                         np.nan, 0.15, 0.00, 0.05, 0.10,
                         np.nan, 0.00, 0.05, 0.15, 0.10],
    'nivel_satisfacao': ['Bom', 'Excelente', 'Regular', 'Bom', np.nan,
                         'Excelente', 'Bom', 'Regular', 'Bom', 'Excelente',
                         np.nan, 'Regular', 'Bom', 'Excelente', 'Bom',
                         'Regular', np.nan, 'Bom', 'Excelente', 'Regular']
})

print("DataFrame criado com sucesso!")
print(f"Shape: {df.shape}")
df.head()

DataFrame criado com sucesso!
Shape: (20, 10)

,id_pedido,data_pedido,vendedor,regiao,produto,categoria,quantidade,preco_unitario,desconto_pct,nivel_satisfacao
0,1001,15/01/2024,Alice,Sudeste,Notebook,Eletrônico,2.0,3500.0,0.05,Bom
1,1002,23/01/2024,Bruno,Nordeste,Geladeira,Eletrodoméstico,1.0,2800.0,NaN,Excelente
2,1003,02/02/2024,Alice,Sudeste,Smartphone,Eletrônico,3.0,1200.0,0.10,Regular
3,1004,14/02/2024,NaN,Sul,"TV 55""",Eletrônico,1.0,4500.0,0.00,Bom
4,1005,28/02/2024,Carlos,Centro-Oeste,Cadeira Gamer,Móvel,4.0,750.0,0.15,NaN

### Questão 1 🟢 FÁCIL — 0.3 pt

**Dimensões do DataFrame**

Qual é o número de linhas e colunas do DataFrame `df`? Escreva o comando que retorna uma tupla `(linhas, colunas)`.

In [2]:
df.shape

(20, 10)

### Questão 2 🟢 FÁCIL — 0.3 pt

**Tipos de Dados**

Exiba o tipo de dado (dtype) de cada coluna do DataFrame.

In [3]:
df.dtypes

id_pedido             int64
data_pedido          object
vendedor             object
regiao               object
produto              object
categoria            object
quantidade          float64
preco_unitario      float64
desconto_pct        float64
nivel_satisfacao     object
dtype: object

### Questão 3 🟢 FÁCIL — 0.3 pt

**Estatísticas Descritivas**

Gere as estatísticas descritivas das colunas numéricas do DataFrame (contagem, média, desvio padrão, mínimo, quartis e máximo).

In [4]:
df.describe()

        id_pedido  quantidade  preco_unitario  desconto_pct
count    20.00000   18.000000       20.000000     16.000000
mean   1010.50000    2.222222     2337.500000      0.068750
std       5.91608    1.215370     1387.484945      0.054391
min    1001.00000    1.000000      720.000000      0.000000
25%    1005.75000    1.000000      937.500000      0.037500
50%    1010.50000    2.000000     2700.000000      0.050000
75%    1015.25000    3.000000     3525.000000      0.100000
max    1020.00000    5.000000     4500.000000      0.150000

### Questão 4 🟢 FÁCIL — 0.3 pt

**Contagem de Valores Ausentes**

Conte quantos valores ausentes (NaN) existem em cada coluna do DataFrame.

In [5]:
df.isnull().sum()

id_pedido           0
data_pedido         0
vendedor            3
regiao              0
produto             0
categoria           0
quantidade          2
preco_unitario      0
desconto_pct        4
nivel_satisfacao    3
dtype: int64

### Questão 5 🟢 FÁCIL — 0.3 pt

**Seleção de Colunas**

Selecione apenas as colunas `produto` e `preco_unitario` do DataFrame.

In [6]:
df[['produto', 'preco_unitario']]

          produto  preco_unitario
0        Notebook          3500.0
1       Geladeira          2800.0
2      Smartphone          1200.0
3          TV 55"          4500.0
4   Cadeira Gamer           750.0
5        Notebook          3600.0
6          Tablet           900.0
7       Geladeira          2750.0
8      Smartphone          1150.0
9          TV 55"          4200.0
10       Notebook          3400.0
11  Cadeira Gamer           800.0
12         Tablet           950.0
13      Geladeira          2900.0
14       Notebook          3700.0
15     Smartphone          1100.0
16         TV 55"          4300.0
17         Tablet           880.0
18  Cadeira Gamer           720.0
19      Geladeira          2650.0

### Questão 6 🟢 FÁCIL — 0.3 pt

**Primeiras Linhas**

Exiba as **3 primeiras** linhas do DataFrame.

In [7]:
df.head(3)

,id_pedido,data_pedido,vendedor,regiao,produto,categoria,quantidade,preco_unitario,desconto_pct,nivel_satisfacao
0,1001,15/01/2024,Alice,Sudeste,Notebook,Eletrônico,2.0,3500.0,0.05,Bom
1,1002,23/01/2024,Bruno,Nordeste,Geladeira,Eletrodoméstico,1.0,2800.0,NaN,Excelente
2,1003,02/02/2024,Alice,Sudeste,Smartphone,Eletrônico,3.0,1200.0,0.10,Regular

### Questão 7 🟢 FÁCIL — 0.3 pt

**Filtro por Igualdade**

Filtre e exiba apenas os pedidos da região `'Sudeste'`.

In [8]:
df[df['regiao'] == 'Sudeste']

,id_pedido,data_pedido,vendedor,regiao,produto,categoria,quantidade,preco_unitario,desconto_pct,nivel_satisfacao
0,1001,15/01/2024,Alice,Sudeste,Notebook,Eletrônico,2.0,3500.0,0.05,Bom
2,1003,02/02/2024,Alice,Sudeste,Smartphone,Eletrônico,3.0,1200.0,0.10,Regular
5,1006,05/03/2024,Bruno,Sudeste,Notebook,Eletrônico,2.0,3600.0,0.05,Excelente
9,1010,25/04/2024,Bruno,Sudeste,"TV 55""",Eletrônico,1.0,4200.0,0.05,Excelente
13,1014,07/06/2024,Alice,Sudeste,Geladeira,Eletrodoméstico,NaN,2900.0,0.05,Excelente
15,1016,04/07/2024,Carlos,Sudeste,Smartphone,Eletrônico,4.0,1100.0,NaN,Regular

### Questão 8 🟢 FÁCIL — 0.3 pt

**Seleção por Posição — `.iloc`**

Use `.iloc` para selecionar as linhas de **posição 2 a 4** (inclusive, ou seja, índices 2, 3 e 4).

In [9]:
df.iloc[2:5]

,id_pedido,data_pedido,vendedor,regiao,produto,categoria,quantidade,preco_unitario,desconto_pct,nivel_satisfacao
2,1003,02/02/2024,Alice,Sudeste,Smartphone,Eletrônico,3.0,1200.0,0.10,Regular
3,1004,14/02/2024,NaN,Sul,"TV 55""",Eletrônico,1.0,4500.0,0.00,Bom
4,1005,28/02/2024,Carlos,Centro-Oeste,Cadeira Gamer,Móvel,4.0,750.0,0.15,NaN

### Questão 9 🟢 FÁCIL — 0.3 pt

**Criação de Nova Coluna**

Crie a coluna `valor_total` como o produto de `quantidade` × `preco_unitario`.

> ⚠️ **Atenção:** esta coluna será usada nas questões seguintes — execute esta célula antes de continuar.

In [10]:
df['valor_total'] = df['quantidade'] * df['preco_unitario']

df.head()

,id_pedido,data_pedido,vendedor,regiao,produto,categoria,quantidade,preco_unitario,desconto_pct,nivel_satisfacao,valor_total
0,1001,15/01/2024,Alice,Sudeste,Notebook,Eletrônico,2.0,3500.0,0.05,Bom,7000.0
1,1002,23/01/2024,Bruno,Nordeste,Geladeira,Eletrodoméstico,1.0,2800.0,NaN,Excelente,2800.0
2,1003,02/02/2024,Alice,Sudeste,Smartphone,Eletrônico,3.0,1200.0,0.10,Regular,3600.0
3,1004,14/02/2024,NaN,Sul,"TV 55""",Eletrônico,1.0,4500.0,0.00,Bom,4500.0
4,1005,28/02/2024,Carlos,Centro-Oeste,Cadeira Gamer,Móvel,4.0,750.0,0.15,NaN,3000.0

### Questão 10 🟢 FÁCIL — 0.3 pt

**Resumo Geral do DataFrame**

Exiba um resumo geral do DataFrame mostrando os tipos de dados, a contagem de valores não-nulos e o uso de memória.

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_pedido         20 non-null     int64
 1   data_pedido       20 non-null     object
 2   vendedor          17 non-null     object
 3   regiao            20 non-null     object
 4   produto           20 non-null     object
 5   categoria         20 non-null     object
 6   quantidade        18 non-null     float64
 7   preco_unitario    20 non-null     float64
 8   desconto_pct      16 non-null     float64
 9   nivel_satisfacao  17 non-null     object
 10  valor_total       18 non-null     float64
dtypes: float64(4), int64(1), object(6)
memory usage: 1.8+ KB

---
## 🟡 Questões Médias — 0,6 ponto cada

### Questão 11 🟡 MÉDIO — 0.6 pt

**Máscara Booleana Composta**

Complete o código para filtrar pedidos onde **`preco_unitario > 2000`** E **`categoria == 'Eletrônico'`** usando uma máscara booleana.

In [12]:
mascara = (df['preco_unitario'] > 2000) & (df['categoria'] == 'Eletrônico')
resultado = df[mascara]
print(f"Pedidos encontrados: {len(resultado)}")
resultado

Pedidos encontrados: 7

,id_pedido,data_pedido,vendedor,regiao,produto,categoria,quantidade,preco_unitario,desconto_pct,nivel_satisfacao,valor_total
0,1001,15/01/2024,Alice,Sudeste,Notebook,Eletrônico,2.0,3500.0,0.05,Bom,7000.0
3,1004,14/02/2024,NaN,Sul,"TV 55""",Eletrônico,1.0,4500.0,0.00,Bom,4500.0
5,1006,05/03/2024,Bruno,Sudeste,Notebook,Eletrônico,2.0,3600.0,0.05,Excelente,7200.0
9,1010,25/04/2024,Bruno,Sudeste,"TV 55""",Eletrônico,1.0,4200.0,0.05,Excelente,4200.0
10,1011,03/05/2024,Alice,Centro-Oeste,Notebook,Eletrônico,3.0,3400.0,NaN,NaN,10200.0
14,1015,20/06/2024,NaN,Sul,Notebook,Eletrônico,2.0,3700.0,0.10,Bom,7400.0
16,1017,18/07/2024,Bruno,Nordeste,"TV 55""",Eletrônico,1.0,4300.0,0.00,NaN,4300.0

### Questão 12 🟡 MÉDIO — 0.6 pt

**Tratamento de Valores Ausentes — fillna + média**

Complete o código para tratar os valores ausentes: preencha `desconto_pct` com `0.0` e `quantidade` com a **média** da coluna.

In [13]:
df_trat = df.copy()

# Preencha desconto_pct com 0.0
df_trat['desconto_pct'] = df_trat['desconto_pct'].fillna(0.0)

# Preencha quantidade com a média da coluna
df_trat['quantidade'] = df_trat['quantidade'].fillna(df_trat['quantidade'].mean())

print(df_trat.isnull().sum())

id_pedido           0
data_pedido         0
vendedor            3
regiao              0
produto             0
categoria           0
quantidade          0
preco_unitario      0
desconto_pct        0
nivel_satisfacao    3
valor_total         2
dtype: int64

### Questão 13 🟡 MÉDIO — 0.6 pt

**Conversão de Datas e Extração de Componentes**

Complete o código para converter a coluna `data_pedido` (string no formato `'dd/mm/yyyy'`) para o tipo `datetime` e criar a coluna `mes_pedido` com o número do mês.

In [14]:
df['data_pedido'] = pd.to_datetime(df['data_pedido'], format='%d/%m/%Y')
df['mes_pedido']   = df['data_pedido'].dt.month
df[['data_pedido', 'mes_pedido']].head()

  data_pedido  mes_pedido
0  2024-01-15           1
1  2024-01-23           1
2  2024-02-02           2
3  2024-02-14           2
4  2024-02-28           2

### Questão 14 🟡 MÉDIO — 0.6 pt

**Agrupamento e Ordenação — groupby + sort_values**

Use `groupby` para calcular a **soma** de `valor_total` por `regiao` e ordene o resultado do **maior para o menor**.

In [15]:
resultado = df.groupby('regiao')['valor_total'].sum().sort_values(ascending=False)
resultado

regiao
Sudeste         26400.0
Centro-Oeste    15850.0
Sul             15640.0
Norte            8740.0
Nordeste         8050.0
Name: valor_total, dtype: float64

### Questão 15 🟡 MÉDIO — 0.6 pt

**Seleção com `.loc` — máscara + colunas**

Use `.loc` para selecionar as colunas `vendedor`, `produto` e `valor_total` somente das linhas onde `nivel_satisfacao == 'Excelente'`.

In [16]:
resultado = df.loc[df['nivel_satisfacao'] == 'Excelente', ['vendedor', 'produto', 'valor_total']]
resultado

   vendedor        produto  valor_total
1     Bruno      Geladeira       2800.0
5     Bruno       Notebook       7200.0
9     Bruno         TV 55"       4200.0
13    Alice      Geladeira          NaN
18   Carlos  Cadeira Gamer       1440.0

---
## 🔴 Questões Difíceis — 0,8 ponto cada

### Questão 16 🔴 DIFÍCIL — 0.8 pt

**Pivot Table**

Complete o código para criar uma pivot table com a **média** de `valor_total` por `regiao` (linhas) e `categoria` (colunas).

In [17]:
pivot = pd.pivot_table(
    df,
    values='valor_total',
    index='regiao',
    columns='categoria',
    aggfunc='mean'
)
pivot

categoria     Eletrodoméstico    Eletrônico   Móvel
regiao
Centro-Oeste           2650.0  10200.000000  3000.0
Nordeste               2800.0   2625.000000     NaN
Norte                     NaN   3570.000000  1600.0
Sudeste                   NaN   5280.000000     NaN
Sul                       NaN   4733.333333  1440.0

### Questão 17 🔴 DIFÍCIL — 0.8 pt

**Agregação com .agg() e Nomes Personalizados**

Complete o script usando `.agg()` para calcular, por `categoria`: a **soma** de `valor_total` (→ `total_vendas`), a **média** de `preco_unitario` (→ `preco_medio`) e a **contagem** de pedidos (→ `num_pedidos`).

In [18]:
resumo = df.groupby('categoria').agg(
    total_vendas = ('valor_total',    'sum'),
    preco_medio  = ('preco_unitario', 'mean'),
    num_pedidos  = ('id_pedido',      'count')
)
resumo

                 total_vendas  preco_medio  num_pedidos
categoria
Eletrodoméstico        5450.0  2775.000000            4
Eletrônico            63190.0  2567.692308           13
Móvel                  6040.0   756.666667            3

### Questão 18 🔴 DIFÍCIL — 0.8 pt

**Variável Categórica Ordinal e Filtro Comparativo**

Complete o código para: (a) converter `nivel_satisfacao` em variável categórica **ordinal** com a ordem `Ruim < Regular < Bom < Excelente`; (b) filtrar apenas pedidos com satisfação **maior que** `'Regular'`.

In [19]:
ordem = ['Ruim', 'Regular', 'Bom', 'Excelente']

df['nivel_satisfacao'] = pd.Categorical(
    df['nivel_satisfacao'],
    categories=ordem,
    ordered=True
)

# Filtrar apenas satisfação > 'Regular'
df_filtrado = df[df['nivel_satisfacao'] > 'Regular']
df_filtrado[['produto', 'nivel_satisfacao']]

          produto nivel_satisfacao
0        Notebook              Bom
1       Geladeira        Excelente
3          TV 55"              Bom
5        Notebook        Excelente
6          Tablet              Bom
8      Smartphone              Bom
9          TV 55"        Excelente
12         Tablet              Bom
13      Geladeira        Excelente
14       Notebook              Bom
17         Tablet              Bom
18  Cadeira Gamer        Excelente

### Questão 19 🔴 DIFÍCIL — 0.8 pt

**Discretização por Frequência — pd.qcut()**

Complete o código para discretizar `preco_unitario` em **4 faixas de igual frequência** usando `pd.qcut()`, com labels `['Econômico', 'Padrão', 'Premium', 'VIP']`. Em seguida, exiba a contagem de pedidos em cada faixa.

In [20]:
df['faixa_preco'] = pd.qcut(
    df['preco_unitario'],
    q=4,
    labels=['Econômico', 'Padrão', 'Premium', 'VIP'],
    duplicates='drop'
)
print(df['faixa_preco'].value_counts())

faixa_preco
Econômico    5
Padrão       5
Premium      5
VIP          5
Name: count, dtype: int64

### Questão 20 🔴 DIFÍCIL — 0.8 pt

**Percentual de Ausentes + Discretização Manual — pd.cut()**

Complete o script que: **(a)** calcula o percentual de ausentes por coluna; **(b)** exibe apenas colunas com ausência > 0%; **(c)** cria faixas manuais de `preco_unitario` com `pd.cut()` usando fronteiras `[0, 1000, 2000, 3000, 5000]` e labels `['Baixo', 'Médio', 'Alto', 'Premium']`.

In [21]:
# (a) Percentual de ausentes
pct_ausentes = (df.isnull().sum() / len(df) * 100).round(2)

# (b) Exibir apenas colunas com ausência > 0%
print(pct_ausentes[pct_ausentes > 0])

# (c) Discretizar preco_unitario com fronteiras manuais
df['faixa_manual'] = pd.cut(
    df['preco_unitario'],
    bins=[0, 1000, 2000, 3000, 5000],
    labels=['Baixo', 'Médio', 'Alto', 'Premium'],
    include_lowest=True
)
df[['preco_unitario', 'faixa_manual']].head(8)

vendedor            15.0
quantidade          10.0
desconto_pct        20.0
nivel_satisfacao    15.0
valor_total         10.0
dtype: float64

   preco_unitario faixa_manual
0          3500.0      Premium
1          2800.0         Alto
2          1200.0        Médio
3          4500.0      Premium
4           750.0        Baixo
5          3600.0      Premium
6           900.0        Baixo
7          2750.0         Alto